// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artists.sql

package sqlc

import (
	"context"
)

const upsertArtist = `-- name: UpsertArtist :one
INSERT INTO artists (mbid, deezer_id, name, disambiguation, image_url)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (mbid) DO UPDATE
    SET name = EXCLUDED.name,
        deezer_id = COALESCE(EXCLUDED.deezer_id, artists.deezer_id),
        updated_at = now()
RETURNING id, mbid, deezer_id, name, disambiguation, image_url, created_at, updated_at
`

type UpsertArtistParams struct {
	Mbid           string  `json:"mbid"`
	DeezerID       *string `json:"deezer_id"`
	Name           string  `json:"name"`
	Disambiguation *string `json:"disambiguation"`
	ImageUrl       *string `json:"image_url"`
}

func (q *Queries) UpsertArtist(ctx context.Context, arg UpsertArtistParams) (Artist, error) {
	row := q.db.QueryRow(ctx, upsertArtist,
		arg.Mbid,
		arg.DeezerID,
		arg.Name,
		arg.Disambiguation,
		arg.ImageUrl,
	)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Mbid,
		&i.DeezerID,
		&i.Name,
		&i.Disambiguation,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
