// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artists.sql

package sqlc

import (
	"context"
)

const upsertArtist = `-- name: UpsertArtist :one
INSERT INTO artists (mbid, deezer_id, name, disambiguation, image_url)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (mbid) DO UPDATE
    SET name = EXCLUDED.name,
        deezer_id = COALESCE(EXCLUDED.deezer_id, artists.deezer_id),
        disambiguation = COALESCE(EXCLUDED.disambiguation, artists.disambiguation),
        image_url = COALESCE(EXCLUDED.image_url, artists.image_url),
        updated_at = now()
RETURNING id, mbid, deezer_id, name, disambiguation, image_url, created_at, updated_at
`

type UpsertArtistParams struct {
	Mbid           string  `json:"mbid"`
	DeezerID       *string `json:"deezer_id"`
	Name           string  `json:"name"`
	Disambiguation *string `json:"disambiguation"`
	ImageUrl       *string `json:"image_url"`
}

// The SET list below is deliberately exhaustive over every mutable metadata
// column on artists (WR-01, G-02-2a): a column left out of it is a column
// this table silently refuses to ever update again on a re-add, and because
// Service.Add builds the response Entry from this query's returned row, the
// caller is handed back the stale value with a 201 as though the write
// succeeded. name is NOT NULL and required on every add (D-04), so it is
// always refreshed unconditionally. deezer_id, disambiguation and image_url
// are all nullable, caller-optional metadata, so each uses
// COALESCE(EXCLUDED.<col>, artists.<col>): a nil/omitted field means "the
// caller said nothing about this field", never "blank it".
func (q *Queries) UpsertArtist(ctx context.Context, arg UpsertArtistParams) (Artist, error) {
	row := q.db.QueryRow(ctx, upsertArtist,
		arg.Mbid,
		arg.DeezerID,
		arg.Name,
		arg.Disambiguation,
		arg.ImageUrl,
	)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Mbid,
		&i.DeezerID,
		&i.Name,
		&i.Disambiguation,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
