// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceGroupTrackCountBaseline = `-- name: AdvanceGroupTrackCountBaseline :many
WITH existing AS (
    SELECT track_count FROM events
    WHERE event_type = 'new_release' AND source = 'musicbrainz' AND external_id = $1
    FOR UPDATE
)
UPDATE events e
SET track_count = $2
FROM existing
WHERE e.event_type = 'new_release' AND e.source = 'musicbrainz' AND e.external_id = $1
  AND (existing.track_count IS NULL OR $2::int > existing.track_count)
RETURNING existing.track_count AS previous_track_count
`

type AdvanceGroupTrackCountBaselineParams struct {
	ExternalID string `json:"external_id"`
	TrackCount *int32 `json:"track_count"`
}

// Atomic replacement (PERF-04, 11-RESEARCH.md Pattern 2) for the former
// two-statement GroupTrackCountBaseline SELECT + SetGroupTrackCountBaseline
// UPDATE -- those two round trips left a check-then-act window where two
// concurrent callers racing the same release group could both read the old
// baseline before either wrote, letting the second writer silently clobber
// the first writer's correct, higher value with its own stale one. This
// statement closes that window entirely rather than narrowing it: the CTE's
// FOR UPDATE takes a row lock on the group's own new_release row, so a
// second concurrent caller racing the same external_id blocks on that lock
// until the first transaction commits, then re-evaluates against the
// just-committed value.
//
// Zero rows returned means no advance happened: the fresh count was not a
// genuine increase over the already-committed baseline (D-02's "equal or
// lower: no event" case, strictly greater-than, now enforced by Postgres
// itself). One row returned means the write landed; previous_track_count
// NULL vs non-NULL is the has_baseline distinction the removed
// GroupTrackCountBaseline query used to report, letting the caller keep
// branching on "silently established" vs "advanced, fire an event" from
// this one call's result alone.
//
// Keyed on external_id (not release_group_mbid, which the removed read
// query used) -- a deliberate narrowing: for a musicbrainz new_release row,
// external_id and release_group_mbid hold the same release-group MBID (see
// internal/detection/musicbrainz.go's new_release insert), and it is the
// new_release row's own track_count that the removed write query mutated,
// so this statement reads exactly the value the old pair wrote.
func (q *Queries) AdvanceGroupTrackCountBaseline(ctx context.Context, arg AdvanceGroupTrackCountBaselineParams) ([]*int32, error) {
	rows, err := q.db.Query(ctx, advanceGroupTrackCountBaseline, arg.ExternalID, arg.TrackCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*int32
	for rows.Next() {
		var previous_track_count *int32
		if err := rows.Scan(&previous_track_count); err != nil {
			return nil, err
		}
		items = append(items, previous_track_count)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasAnyEvent = `-- name: HasAnyEvent :one
SELECT EXISTS(
    SELECT 1 FROM events WHERE artist_id = $1 AND source = $2
) AS has_any
`

type HasAnyEventParams struct {
	ArtistID int64  `json:"artist_id"`
	Source   string `json:"source"`
}

// D-14's implicit seed-mode check, scoped per-source per D-15: zero
// existing event rows for this artist+source means seed mode.
func (q *Queries) HasAnyEvent(ctx context.Context, arg HasAnyEventParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasAnyEvent, arg.ArtistID, arg.Source)
	var has_any bool
	err := row.Scan(&has_any)
	return has_any, err
}

const hasOlderEvents = `-- name: HasOlderEvents :one
SELECT EXISTS(
    SELECT 1 FROM events
    WHERE ($1::bigint IS NULL OR artist_id = $1::bigint)
      AND ($2::text IS NULL OR event_type = $2::text)
      AND created_at < $3::timestamptz
) AS has_older
`

type HasOlderEventsParams struct {
	ArtistID  *int64             `json:"artist_id"`
	EventType *string            `json:"event_type"`
	Cutoff    pgtype.Timestamptz `json:"cutoff"`
}

// Phase 10 (DATA-02, D-06): answers a question ListEvents' own result page
// cannot -- whether this request's artist_id/event_type scope has ANY event
// older than the retention cutoff, so the frontend can distinguish "no
// events ever" from "events exist but every one of them aged out" (the
// History empty state cannot tell those apart from an empty page alone).
// Mirrors ListEvents' two optional filters exactly (same sqlc.narg casts on
// both sides), but deliberately omits ListEvents' pagination-position
// parameter: this answers a property of the whole filtered scope, not of
// the current page, so a "Load more" click must not change the answer.
// Uses EXISTS with no LIMIT inside it, following HasAnyEvent's existing
// idiom in this file --
// EXISTS already short-circuits on the first matching row. created_at <
// cutoff (strict less-than) is the exact complement of ListEvents' >=, so a
// row exactly at the boundary is never double-counted as both visible and
// older (D-04 stays consistent across both queries).
func (q *Queries) HasOlderEvents(ctx context.Context, arg HasOlderEventsParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasOlderEvents, arg.ArtistID, arg.EventType, arg.Cutoff)
	var has_older bool
	err := row.Scan(&has_older)
	return has_older, err
}

const insertEvent = `-- name: InsertEvent :execrows
INSERT INTO events (
    artist_id, source, event_type, external_id, release_group_mbid,
    title, artist_name, release_date, cover_art_url, track_count, notified_at,
    previous_track_count, release_type
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
ON CONFLICT (event_type, source, external_id) DO NOTHING
`

type InsertEventParams struct {
	ArtistID           int64              `json:"artist_id"`
	Source             string             `json:"source"`
	EventType          string             `json:"event_type"`
	ExternalID         string             `json:"external_id"`
	ReleaseGroupMbid   *string            `json:"release_group_mbid"`
	Title              string             `json:"title"`
	ArtistName         string             `json:"artist_name"`
	ReleaseDate        *string            `json:"release_date"`
	CoverArtUrl        *string            `json:"cover_art_url"`
	TrackCount         *int32             `json:"track_count"`
	NotifiedAt         pgtype.Timestamptz `json:"notified_at"`
	PreviousTrackCount *int32             `json:"previous_track_count"`
	ReleaseType        *string            `json:"release_type"`
}

// 0 rows affected means the dedup key (event_type, source, external_id)
// already existed (D-20) -- the caller does not treat this as an error,
// only as "not newly detected." Deliberately not the
// COALESCE(EXCLUDED.col, table.col) refresh shape UpsertArtist uses,
// because a re-detected event must keep its original snapshot (D-20):
// plain DO NOTHING, no SET clause at all. previous_track_count and
// release_type (Phase 5's D-04/Pitfall-3 columns) are appended after the
// existing eleven columns, as $12/$13, so every pre-existing positional
// parameter keeps its number -- D-20's write-once guarantee applies to
// these two snapshot columns exactly as it does to the original nine.
func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertEvent,
		arg.ArtistID,
		arg.Source,
		arg.EventType,
		arg.ExternalID,
		arg.ReleaseGroupMbid,
		arg.Title,
		arg.ArtistName,
		arg.ReleaseDate,
		arg.CoverArtUrl,
		arg.TrackCount,
		arg.NotifiedAt,
		arg.PreviousTrackCount,
		arg.ReleaseType,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listEvents = `-- name: ListEvents :many
SELECT id, artist_id, source, event_type, external_id, release_group_mbid,
       title, artist_name, release_date, cover_art_url, track_count,
       previous_track_count, release_type, notified_at, created_at
FROM events
WHERE ($1::bigint IS NULL OR artist_id = $1::bigint)
  AND ($2::text IS NULL OR event_type = $2::text)
  AND ($3::bigint IS NULL OR id < $3::bigint)
  AND created_at >= $4::timestamptz
ORDER BY id DESC
LIMIT $5
`

type ListEventsParams struct {
	ArtistID  *int64             `json:"artist_id"`
	EventType *string            `json:"event_type"`
	Cursor    *int64             `json:"cursor"`
	Cutoff    pgtype.Timestamptz `json:"cutoff"`
	PageSize  int32              `json:"page_size"`
}

type ListEventsRow struct {
	ID                 int64              `json:"id"`
	ArtistID           int64              `json:"artist_id"`
	Source             string             `json:"source"`
	EventType          string             `json:"event_type"`
	ExternalID         string             `json:"external_id"`
	ReleaseGroupMbid   *string            `json:"release_group_mbid"`
	Title              string             `json:"title"`
	ArtistName         string             `json:"artist_name"`
	ReleaseDate        *string            `json:"release_date"`
	CoverArtUrl        *string            `json:"cover_art_url"`
	TrackCount         *int32             `json:"track_count"`
	PreviousTrackCount *int32             `json:"previous_track_count"`
	ReleaseType        *string            `json:"release_type"`
	NotifiedAt         pgtype.Timestamptz `json:"notified_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

// Phase 6's HIST-01 history feed backing query (D-05): one global
// chronological read across all watched artists, newest first -- not a
// per-artist drill-down. Ordered and keyset-paginated on id DESC, not
// created_at: this file's own ListUnnotified comment already documents why
// created_at alone is not a unique order -- a seed cycle inserts many rows
// sharing one created_at timestamp, so ordering by it alone would make page
// boundaries non-deterministic across a "load more" click (06-RESEARCH.md
// Pattern 2, Pitfall 2). id (BIGSERIAL) is already unique and monotonic and
// needs no secondary tiebreak column.
//
// artist_id, event_type and cursor are all optional sqlc.narg filters, each
// cast on both sides of its "IS NULL OR" predicate so sqlc's type inference
// has no ambiguity. "IS NULL OR" keeps one static SQL string sqlc can
// type-check, instead of building WHERE clauses in Go (06-RESEARCH.md
// Anti-Patterns). cursor is absent on the first page and set to the previous
// page's last row's id on subsequent pages.
//
// Phase 10 (DATA-02, D-01/D-04): this is the ONLY query in this file that
// ever gets a retention cutoff. cutoff is sqlc.arg, not sqlc.narg -- it is
// never caller-optional, so there is no code path where a caller passes a
// null cutoff and gets back unfiltered, out-of-window rows (T-10-03). The
// comparison is >=, not >: an event exactly at the boundary stays visible
// (D-04). This is a read-side filter only, nothing is deleted -- an
// aged-out row stays fully present and fully visible to every query below
// that intentionally has no cutoff: ListExternalIDs (dedup keys),
// HasAnyEvent (seed-mode), AdvanceGroupTrackCountBaseline (deluxe
// baselines), and ListUnnotified (pending notifications). Adding this predicate to any of
// those four is the exact regression Phase 10's success criteria 3-5 exist
// to catch -- do not "fix" them to also filter by retention.
func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]ListEventsRow, error) {
	rows, err := q.db.Query(ctx, listEvents,
		arg.ArtistID,
		arg.EventType,
		arg.Cursor,
		arg.Cutoff,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventsRow
	for rows.Next() {
		var i ListEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.ArtistID,
			&i.Source,
			&i.EventType,
			&i.ExternalID,
			&i.ReleaseGroupMbid,
			&i.Title,
			&i.ArtistName,
			&i.ReleaseDate,
			&i.CoverArtUrl,
			&i.TrackCount,
			&i.PreviousTrackCount,
			&i.ReleaseType,
			&i.NotifiedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExternalIDs = `-- name: ListExternalIDs :many
SELECT external_id FROM events WHERE artist_id = $1 AND source = $2 AND event_type = $3
`

type ListExternalIDsParams struct {
	ArtistID  int64  `json:"artist_id"`
	Source    string `json:"source"`
	EventType string `json:"event_type"`
}

// Feeds the fresh-vs-seen diff (D-10): a Detector builds a
// map[string]struct{} from this result and skips any externally-fetched
// id already present.
func (q *Queries) ListExternalIDs(ctx context.Context, arg ListExternalIDsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listExternalIDs, arg.ArtistID, arg.Source, arg.EventType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var external_id string
		if err := rows.Scan(&external_id); err != nil {
			return nil, err
		}
		items = append(items, external_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnnotified = `-- name: ListUnnotified :many
SELECT id, artist_id, source, event_type, external_id, release_group_mbid, title, artist_name, release_date, cover_art_url, track_count, notified_at, created_at, previous_track_count, release_type FROM events WHERE notified_at IS NULL ORDER BY created_at ASC, id ASC
`

// D-11's Phase 5 groundwork: SELECT WHERE notified_at IS NULL, ORDER BY
// created_at ASC, id ASC for a deterministic total order (a plain
// created_at ordering alone is not unique -- a seed cycle's rows share one
// timestamp, see seedNotifiedAt). This is also the instrument plan 04-02's
// own tests use to prove seeded rows are excluded (D-13).
func (q *Queries) ListUnnotified(ctx context.Context) ([]Event, error) {
	rows, err := q.db.Query(ctx, listUnnotified)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.ArtistID,
			&i.Source,
			&i.EventType,
			&i.ExternalID,
			&i.ReleaseGroupMbid,
			&i.Title,
			&i.ArtistName,
			&i.ReleaseDate,
			&i.CoverArtUrl,
			&i.TrackCount,
			&i.NotifiedAt,
			&i.CreatedAt,
			&i.PreviousTrackCount,
			&i.ReleaseType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotified = `-- name: MarkNotified :execrows
UPDATE events SET notified_at = now() WHERE id = $1 AND notified_at IS NULL
`

// Precondition: only ever called after discord.Client.Send has confirmed a
// 204 for this row (D-09) -- never before. The AND notified_at IS NULL
// predicate is load-bearing, not decorative: it makes the ack idempotent, so
// a second acknowledgement of an already-delivered row affects zero rows
// instead of overwriting the recorded delivery time.
func (q *Queries) MarkNotified(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, markNotified, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
