// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const groupTrackCountBaseline = `-- name: GroupTrackCountBaseline :one
SELECT COALESCE(MAX(track_count), 0)::int AS baseline,
       COUNT(track_count) > 0 AS has_baseline
FROM events
WHERE source = 'musicbrainz' AND release_group_mbid = $1
`

type GroupTrackCountBaselineRow struct {
	Baseline    int32 `json:"baseline"`
	HasBaseline bool  `json:"has_baseline"`
}

// Plan 04-04's baseline lookup for a release-group's deluxe-change
// comparison (D-01/D-02), option-a resolution (04-01's Task 1 checkpoint):
// track_count lives directly on the events row, not a second table.
// has_baseline distinguishes "no baseline recorded yet" (COUNT is 0, this
// group has never had track_count populated) from "baseline recorded as
// zero" -- collapsing those two into one COALESCE(...,0) is exactly
// 04-RESEARCH.md Pitfall #1's false-positive mechanism: the caller MUST
// branch on has_baseline before comparing, never compare against baseline
// alone.
func (q *Queries) GroupTrackCountBaseline(ctx context.Context, releaseGroupMbid *string) (GroupTrackCountBaselineRow, error) {
	row := q.db.QueryRow(ctx, groupTrackCountBaseline, releaseGroupMbid)
	var i GroupTrackCountBaselineRow
	err := row.Scan(&i.Baseline, &i.HasBaseline)
	return i, err
}

const hasAnyEvent = `-- name: HasAnyEvent :one
SELECT EXISTS(
    SELECT 1 FROM events WHERE artist_id = $1 AND source = $2
) AS has_any
`

type HasAnyEventParams struct {
	ArtistID int64  `json:"artist_id"`
	Source   string `json:"source"`
}

// D-14's implicit seed-mode check, scoped per-source per D-15: zero
// existing event rows for this artist+source means seed mode.
func (q *Queries) HasAnyEvent(ctx context.Context, arg HasAnyEventParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasAnyEvent, arg.ArtistID, arg.Source)
	var has_any bool
	err := row.Scan(&has_any)
	return has_any, err
}

const insertEvent = `-- name: InsertEvent :execrows
INSERT INTO events (
    artist_id, source, event_type, external_id, release_group_mbid,
    title, artist_name, release_date, cover_art_url, track_count, notified_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
ON CONFLICT (event_type, source, external_id) DO NOTHING
`

type InsertEventParams struct {
	ArtistID         int64              `json:"artist_id"`
	Source           string             `json:"source"`
	EventType        string             `json:"event_type"`
	ExternalID       string             `json:"external_id"`
	ReleaseGroupMbid *string            `json:"release_group_mbid"`
	Title            string             `json:"title"`
	ArtistName       string             `json:"artist_name"`
	ReleaseDate      *string            `json:"release_date"`
	CoverArtUrl      *string            `json:"cover_art_url"`
	TrackCount       *int32             `json:"track_count"`
	NotifiedAt       pgtype.Timestamptz `json:"notified_at"`
}

// 0 rows affected means the dedup key (event_type, source, external_id)
// already existed (D-20) -- the caller does not treat this as an error,
// only as "not newly detected." Deliberately not the
// COALESCE(EXCLUDED.col, table.col) refresh shape UpsertArtist uses,
// because a re-detected event must keep its original snapshot (D-20):
// plain DO NOTHING, no SET clause at all.
func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertEvent,
		arg.ArtistID,
		arg.Source,
		arg.EventType,
		arg.ExternalID,
		arg.ReleaseGroupMbid,
		arg.Title,
		arg.ArtistName,
		arg.ReleaseDate,
		arg.CoverArtUrl,
		arg.TrackCount,
		arg.NotifiedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listExternalIDs = `-- name: ListExternalIDs :many
SELECT external_id FROM events WHERE artist_id = $1 AND source = $2 AND event_type = $3
`

type ListExternalIDsParams struct {
	ArtistID  int64  `json:"artist_id"`
	Source    string `json:"source"`
	EventType string `json:"event_type"`
}

// Feeds the fresh-vs-seen diff (D-10): a Detector builds a
// map[string]struct{} from this result and skips any externally-fetched
// id already present.
func (q *Queries) ListExternalIDs(ctx context.Context, arg ListExternalIDsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listExternalIDs, arg.ArtistID, arg.Source, arg.EventType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var external_id string
		if err := rows.Scan(&external_id); err != nil {
			return nil, err
		}
		items = append(items, external_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnnotified = `-- name: ListUnnotified :many
SELECT id, artist_id, source, event_type, external_id, release_group_mbid, title, artist_name, release_date, cover_art_url, track_count, notified_at, created_at FROM events WHERE notified_at IS NULL ORDER BY created_at ASC, id ASC
`

// D-11's Phase 5 groundwork: SELECT WHERE notified_at IS NULL, ORDER BY
// created_at ASC, id ASC for a deterministic total order (a plain
// created_at ordering alone is not unique -- a seed cycle's rows share one
// timestamp, see seedNotifiedAt). This is also the instrument plan 04-02's
// own tests use to prove seeded rows are excluded (D-13).
func (q *Queries) ListUnnotified(ctx context.Context) ([]Event, error) {
	rows, err := q.db.Query(ctx, listUnnotified)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.ArtistID,
			&i.Source,
			&i.EventType,
			&i.ExternalID,
			&i.ReleaseGroupMbid,
			&i.Title,
			&i.ArtistName,
			&i.ReleaseDate,
			&i.CoverArtUrl,
			&i.TrackCount,
			&i.NotifiedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setGroupTrackCountBaseline = `-- name: SetGroupTrackCountBaseline :execrows
UPDATE events
SET track_count = $2
WHERE event_type = 'new_release' AND source = 'musicbrainz' AND external_id = $1
`

type SetGroupTrackCountBaselineParams struct {
	ExternalID string `json:"external_id"`
	TrackCount *int32 `json:"track_count"`
}

// Mutates track_count on the group's own new_release row -- this is
// operational baseline state, not the D-12 display snapshot (title/
// artist_name/release_date/cover_art_url), which stays write-once via
// InsertEvent's ON CONFLICT DO NOTHING per D-20. No snapshot column is
// ever written twice by this statement.
func (q *Queries) SetGroupTrackCountBaseline(ctx context.Context, arg SetGroupTrackCountBaselineParams) (int64, error) {
	result, err := q.db.Exec(ctx, setGroupTrackCountBaseline, arg.ExternalID, arg.TrackCount)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
