// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Artist struct {
	ID             int64              `json:"id"`
	Mbid           string             `json:"mbid"`
	DeezerID       *string            `json:"deezer_id"`
	Name           string             `json:"name"`
	Disambiguation *string            `json:"disambiguation"`
	ImageUrl       *string            `json:"image_url"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Event struct {
	ID                 int64              `json:"id"`
	ArtistID           int64              `json:"artist_id"`
	Source             string             `json:"source"`
	EventType          string             `json:"event_type"`
	ExternalID         string             `json:"external_id"`
	ReleaseGroupMbid   *string            `json:"release_group_mbid"`
	Title              string             `json:"title"`
	ArtistName         string             `json:"artist_name"`
	ReleaseDate        *string            `json:"release_date"`
	CoverArtUrl        *string            `json:"cover_art_url"`
	TrackCount         *int32             `json:"track_count"`
	NotifiedAt         pgtype.Timestamptz `json:"notified_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	PreviousTrackCount *int32             `json:"previous_track_count"`
	ReleaseType        *string            `json:"release_type"`
}

type Watchlist struct {
	ID              int64              `json:"id"`
	ArtistID        int64              `json:"artist_id"`
	ReleaseTypes    []string           `json:"release_types"`
	MutedEventTypes []string           `json:"muted_event_types"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}
