// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_settings.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ackDigestBatch = `-- name: AckDigestBatch :exec
WITH acked AS (
    UPDATE events SET notified_at = now()
    WHERE id = ANY($3::bigint[]) AND notified_at IS NULL
    RETURNING id
)
UPDATE notification_settings
SET digest_last_slot_at = $1::timestamptz,
    digest_last_sent_at = COALESCE($2::timestamptz, digest_last_sent_at)
WHERE id = 1
`

type AckDigestBatchParams struct {
	Slot   pgtype.Timestamptz `json:"slot"`
	SentAt pgtype.Timestamptz `json:"sent_at"`
	Ids    []int64            `json:"ids"`
}

// Phase 22 (D-16): the digest send's single-statement batch ack. Acks every
// sent/suppressed event id (idempotent via the same AND notified_at IS NULL
// predicate MarkNotified uses) and advances the singleton row's slot record
// (always) and last-sent watermark (only when something was actually sent --
// sent_at is nil on an empty/suppressed-only skip, so COALESCE leaves the
// watermark untouched) in one atomic statement. No updated_at bump here on
// purpose: updated_at tracks operator writes through PUT
// /settings/notifications, and a scheduler-driven ack is not one. The
// `acked` CTE is deliberately unreferenced by the outer UPDATE: Postgres
// executes every data-modifying CTE in a statement exactly once regardless
// of whether it is read from, so this still acks the events and updates the
// settings row as one atomic statement with no Go transaction --
// sqlc.Querier (internal/db/sqlc/db.go) exposes WithTx only on the concrete
// *Queries, never on the interface every production caller is typed against.
func (q *Queries) AckDigestBatch(ctx context.Context, arg AckDigestBatchParams) error {
	_, err := q.db.Exec(ctx, ackDigestBatch, arg.Slot, arg.SentAt, arg.Ids)
	return err
}

const getNotificationSettings = `-- name: GetNotificationSettings :one
SELECT id, digest_enabled, digest_cadence, digest_last_sent_at, updated_at, digest_last_slot_at FROM notification_settings WHERE id = 1
`

func (q *Queries) GetNotificationSettings(ctx context.Context) (NotificationSetting, error) {
	row := q.db.QueryRow(ctx, getNotificationSettings)
	var i NotificationSetting
	err := row.Scan(
		&i.ID,
		&i.DigestEnabled,
		&i.DigestCadence,
		&i.DigestLastSentAt,
		&i.UpdatedAt,
		&i.DigestLastSlotAt,
	)
	return i, err
}

const updateNotificationSettings = `-- name: UpdateNotificationSettings :one
UPDATE notification_settings
SET digest_enabled      = $1,
    digest_cadence       = $2,
    digest_last_slot_at  = CASE
        WHEN $1 AND (NOT digest_enabled OR digest_cadence <> $2)
            THEN $3::timestamptz
        ELSE digest_last_slot_at
    END,
    updated_at           = now()
WHERE id = 1
RETURNING id, digest_enabled, digest_cadence, digest_last_sent_at, updated_at, digest_last_slot_at
`

type UpdateNotificationSettingsParams struct {
	DigestEnabled bool               `json:"digest_enabled"`
	DigestCadence string             `json:"digest_cadence"`
	ReanchorSlot  pgtype.Timestamptz `json:"reanchor_slot"`
}

// Full-object PUT semantics (no partial-update ambiguity to resolve), and the
// fixed id = 1 predicate is what makes replaying the same body a no-op.
// Phase 22 (D-14): digest_last_slot_at re-anchors to the caller-computed slot
// only when digest mode is being turned on, or the cadence is changing while
// it is already on -- never on a plain no-op replay and never on turning
// digest mode off. The unqualified digest_enabled/digest_cadence on the
// right of the WHEN condition are Postgres's pre-UPDATE row values (a SET
// list's right-hand side evaluates against the row as it was before this
// statement), which is exactly what the re-anchor decision needs.
func (q *Queries) UpdateNotificationSettings(ctx context.Context, arg UpdateNotificationSettingsParams) (NotificationSetting, error) {
	row := q.db.QueryRow(ctx, updateNotificationSettings, arg.DigestEnabled, arg.DigestCadence, arg.ReanchorSlot)
	var i NotificationSetting
	err := row.Scan(
		&i.ID,
		&i.DigestEnabled,
		&i.DigestCadence,
		&i.DigestLastSentAt,
		&i.UpdatedAt,
		&i.DigestLastSlotAt,
	)
	return i, err
}
