// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_settings.sql

package sqlc

import (
	"context"
)

const getNotificationSettings = `-- name: GetNotificationSettings :one
SELECT id, digest_enabled, digest_cadence, digest_last_sent_at, updated_at FROM notification_settings WHERE id = 1
`

func (q *Queries) GetNotificationSettings(ctx context.Context) (NotificationSetting, error) {
	row := q.db.QueryRow(ctx, getNotificationSettings)
	var i NotificationSetting
	err := row.Scan(
		&i.ID,
		&i.DigestEnabled,
		&i.DigestCadence,
		&i.DigestLastSentAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateNotificationSettings = `-- name: UpdateNotificationSettings :one
UPDATE notification_settings
SET digest_enabled = $1,
    digest_cadence  = $2,
    updated_at      = now()
WHERE id = 1
RETURNING id, digest_enabled, digest_cadence, digest_last_sent_at, updated_at
`

type UpdateNotificationSettingsParams struct {
	DigestEnabled bool   `json:"digest_enabled"`
	DigestCadence string `json:"digest_cadence"`
}

// A plain positional UPDATE, not watchlist's CASE-based merge: the route is
// a full-object PUT (no partial-update ambiguity to resolve), and the fixed
// id = 1 predicate is what makes replaying the same body a no-op.
func (q *Queries) UpdateNotificationSettings(ctx context.Context, arg UpdateNotificationSettingsParams) (NotificationSetting, error) {
	row := q.db.QueryRow(ctx, updateNotificationSettings, arg.DigestEnabled, arg.DigestCadence)
	var i NotificationSetting
	err := row.Scan(
		&i.ID,
		&i.DigestEnabled,
		&i.DigestCadence,
		&i.DigestLastSentAt,
		&i.UpdatedAt,
	)
	return i, err
}
