// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	CreateWatchlistEntry(ctx context.Context, arg CreateWatchlistEntryParams) (Watchlist, error)
	// :execrows returns the affected row count in one round trip, which is what
	// lets the service distinguish "deleted" from "there was nothing to delete"
	// without a preceding existence SELECT. A check-then-delete pair would open
	// a window where a concurrent delete lands between the two statements,
	// turning what should be one 204 and one 404 into two 204s; Postgres's
	// row-level lock on this single statement is what makes the split
	// deterministic under concurrency (T-02-15).
	DeleteWatchlistEntry(ctx context.Context, id int64) (int64, error)
	// D-14's implicit seed-mode check, scoped per-source per D-15: zero
	// existing event rows for this artist+source means seed mode.
	HasAnyEvent(ctx context.Context, arg HasAnyEventParams) (bool, error)
	// 0 rows affected means the dedup key (event_type, source, external_id)
	// already existed (D-20) -- the caller does not treat this as an error,
	// only as "not newly detected." Deliberately not the
	// COALESCE(EXCLUDED.col, table.col) refresh shape UpsertArtist uses,
	// because a re-detected event must keep its original snapshot (D-20):
	// plain DO NOTHING, no SET clause at all.
	InsertEvent(ctx context.Context, arg InsertEventParams) (int64, error)
	// Feeds the fresh-vs-seen diff (D-10): a Detector builds a
	// map[string]struct{} from this result and skips any externally-fetched
	// id already present.
	ListExternalIDs(ctx context.Context, arg ListExternalIDsParams) ([]string, error)
	// D-11's Phase 5 groundwork: SELECT WHERE notified_at IS NULL, ORDER BY
	// created_at ASC, id ASC for a deterministic total order (a plain
	// created_at ordering alone is not unique -- a seed cycle's rows share one
	// timestamp, see seedNotifiedAt). This is also the instrument plan 04-02's
	// own tests use to prove seeded rows are excluded (D-13).
	ListUnnotified(ctx context.Context) ([]Event, error)
	// Both watchlist and artists have a column named id -- every selected
	// column is explicitly aliased so sqlc emits a struct carrying both ID
	// (the watchlist entry) and ArtistID (the master artist) rather than
	// silently collapsing them (02-RESEARCH.md Pitfall 4). Name is not unique,
	// so the artist id is a required, not cosmetic, ORDER BY tiebreak: without
	// it, two equally-named artists would come back in whatever order the
	// planner happens to choose, which is non-deterministic across runs.
	ListWatchlist(ctx context.Context) ([]ListWatchlistRow, error)
	Ping(ctx context.Context) (int32, error)
	// The partial-update merge happens inside this statement, not in Go: each
	// axis is resolved by a CASE whose ELSE names the column itself, so the
	// value carried forward for an untouched axis is read from the row version
	// this UPDATE itself locked. Under READ COMMITTED a writer blocked behind
	// another writer's uncommitted change re-evaluates its WHERE clause and SET
	// expressions against the newly committed row once it unblocks -- so the
	// second writer physically cannot persist a value it observed before the
	// first writer committed (G-02-2b, T-02-19). The zero-row case (no matching
	// id, including one deleted concurrently) surfaces as pgx.ErrNoRows, which
	// Service.UpdatePreferences translates to ErrNotFound in one round trip
	// (T-02-20) -- there is no separate unlocked read whose result can go stale.
	//
	// Each axis's "am I being set" signal is carried by its own explicit boolean
	// parameter rather than multiplexed onto the array parameter's nullability:
	// an empty array and an absent key are two different client intents (D-11),
	// and a NULL-means-untouched COALESCE would collapse that distinction.
	UpdateWatchlistPreferences(ctx context.Context, arg UpdateWatchlistPreferencesParams) (UpdateWatchlistPreferencesRow, error)
	// The SET list below is deliberately exhaustive over every mutable metadata
	// column on artists (WR-01, G-02-2a): a column left out of it is a column
	// this table silently refuses to ever update again on a re-add, and because
	// Service.Add builds the response Entry from this query's returned row, the
	// caller is handed back the stale value with a 201 as though the write
	// succeeded. name is NOT NULL and required on every add (D-04), so it is
	// always refreshed unconditionally. deezer_id, disambiguation and image_url
	// are all nullable, caller-optional metadata, so each uses
	// COALESCE(EXCLUDED.<col>, artists.<col>): a nil/omitted field means "the
	// caller said nothing about this field", never "blank it".
	UpsertArtist(ctx context.Context, arg UpsertArtistParams) (Artist, error)
}

var _ Querier = (*Queries)(nil)
