// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package sqlc

import (
	"context"
)

const attachTag = `-- name: AttachTag :execrows
INSERT INTO artist_tags (artist_id, tag_id) VALUES ($1, $2)
ON CONFLICT (artist_id, tag_id) DO NOTHING
`

type AttachTagParams struct {
	ArtistID int64 `json:"artist_id"`
	TagID    int64 `json:"tag_id"`
}

// Rows affected: 1 = new link, 0 = the artist already carried this tag
// (D-21 idempotent attach). The artist_tags_cap_trigger (migration 000010)
// enforces the 10-tag cap; this statement never counts anything itself.
func (q *Queries) AttachTag(ctx context.Context, arg AttachTagParams) (int64, error) {
	result, err := q.db.Exec(ctx, attachTag, arg.ArtistID, arg.TagID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countCarriersForTags = `-- name: CountCarriersForTags :one
SELECT count(DISTINCT w.artist_id)::bigint AS carrier_count
FROM artist_tags link
JOIN watchlist w ON w.artist_id = link.artist_id
WHERE link.tag_id = ANY($1::bigint[])
`

// Watched carriers across one or more tags, each artist counted once even
// when it carries more than one of the given tags (union count, D-19/SC3).
func (q *Queries) CountCarriersForTags(ctx context.Context, tagIds []int64) (int64, error) {
	row := q.db.QueryRow(ctx, countCarriersForTags, tagIds)
	var carrier_count int64
	err := row.Scan(&carrier_count)
	return carrier_count, err
}

const deleteTagCountingCarriers = `-- name: DeleteTagCountingCarriers :one
WITH counted AS (
    SELECT count(w.id)::bigint AS carrier_count
    FROM artist_tags link
    JOIN watchlist w ON w.artist_id = link.artist_id
    WHERE link.tag_id = $1
), deleted AS (
    DELETE FROM tags WHERE id = $1 RETURNING id
)
SELECT deleted.id, counted.carrier_count FROM deleted, counted
`

type DeleteTagCountingCarriersRow struct {
	ID           int64 `json:"id"`
	CarrierCount int64 `json:"carrier_count"`
}

// Both CTEs read the same pre-statement snapshot (Postgres WITH semantics):
// counted's SELECT never sees deleted's cascade removal of artist_tags, so
// the reported count is exactly the watched-carrier count the delete
// removed (TAG-06). Zero rows means the tag did not exist.
func (q *Queries) DeleteTagCountingCarriers(ctx context.Context, tagID int64) (DeleteTagCountingCarriersRow, error) {
	row := q.db.QueryRow(ctx, deleteTagCountingCarriers, tagID)
	var i DeleteTagCountingCarriersRow
	err := row.Scan(&i.ID, &i.CarrierCount)
	return i, err
}

const detachTag = `-- name: DetachTag :execrows
DELETE FROM artist_tags WHERE artist_id = $1 AND tag_id = $2
`

type DetachTagParams struct {
	ArtistID int64 `json:"artist_id"`
	TagID    int64 `json:"tag_id"`
}

// Any affected count is success (D-21): 0 rows means the link was already
// gone, which is not an error for an idempotent detach.
func (q *Queries) DetachTag(ctx context.Context, arg DetachTagParams) (int64, error) {
	result, err := q.db.Exec(ctx, detachTag, arg.ArtistID, arg.TagID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOrCreateTag = `-- name: GetOrCreateTag :one
INSERT INTO tags (name) VALUES ($1)
ON CONFLICT ((lower(name))) DO UPDATE SET name = tags.name
RETURNING id, name
`

type GetOrCreateTagRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

// One statement, no fallback SELECT (D-29): the no-op DO UPDATE is what
// makes RETURNING yield the existing row on a collision, preserving the
// first-entered casing (TAG-03). Conflict target is the tags_name_lower_idx
// expression index from migration 000010.
func (q *Queries) GetOrCreateTag(ctx context.Context, name string) (GetOrCreateTagRow, error) {
	row := q.db.QueryRow(ctx, getOrCreateTag, name)
	var i GetOrCreateTagRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, name FROM tags WHERE lower(name) = lower($1)
`

type GetTagByNameRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

// Used only *after* a tags_name_lower_idx violation, to identify the
// collider (D-22) -- never a pre-check.
func (q *Queries) GetTagByName(ctx context.Context, lower string) (GetTagByNameRow, error) {
	row := q.db.QueryRow(ctx, getTagByName, lower)
	var i GetTagByNameRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getWatchlistArtistID = `-- name: GetWatchlistArtistID :one
SELECT artist_id FROM watchlist WHERE id = $1
`

// Resolves the artist a watchlist entry belongs to, so attach/detach can
// address artist_tags (which keys on artists.id, TAG-07) through the same
// entry id every other watchlist route uses (D-20).
func (q *Queries) GetWatchlistArtistID(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, getWatchlistArtistID, id)
	var artist_id int64
	err := row.Scan(&artist_id)
	return artist_id, err
}

const listTags = `-- name: ListTags :many
SELECT t.id, t.name, count(w.id)::bigint AS carrier_count
FROM tags t
LEFT JOIN artist_tags link ON link.tag_id = t.id
LEFT JOIN watchlist w ON w.artist_id = link.artist_id
GROUP BY t.id, t.name
ORDER BY lower(t.name), t.id
`

type ListTagsRow struct {
	ID           int64  `json:"id"`
	Name         string `json:"name"`
	CarrierCount int64  `json:"carrier_count"`
}

// Watched-only carrier count (D-11): count(w.id) counts a row only when the
// LEFT JOIN watchlist actually matched, so a tag whose only links belong to
// removed artists (or no links at all) still surfaces with count 0 (D-12,
// D-13) instead of being dropped by an inner join. Ordered by lower(name)
// then id: tags_name_lower_idx makes lower(name) unique, so this is a
// total, repeatable order (TAG-05).
func (q *Queries) ListTags(ctx context.Context) ([]ListTagsRow, error) {
	rows, err := q.db.Query(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagsRow
	for rows.Next() {
		var i ListTagsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.CarrierCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameTag = `-- name: RenameTag :one
UPDATE tags SET name = $2 WHERE id = $1 RETURNING id, name
`

type RenameTagParams struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type RenameTagRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

// A plain rename by id. A collision is never checked here -- it surfaces as
// a tags_name_lower_idx unique violation, which Service.Rename maps to
// *CollisionError (D-09, D-22). A case-only rename of the same row cannot
// conflict with its own index entry.
func (q *Queries) RenameTag(ctx context.Context, arg RenameTagParams) (RenameTagRow, error) {
	row := q.db.QueryRow(ctx, renameTag, arg.ID, arg.Name)
	var i RenameTagRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
