// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package sqlc

import (
	"context"
)

const attachTag = `-- name: AttachTag :execrows
INSERT INTO artist_tags (artist_id, tag_id) VALUES ($1, $2)
ON CONFLICT (artist_id, tag_id) DO NOTHING
`

type AttachTagParams struct {
	ArtistID int64 `json:"artist_id"`
	TagID    int64 `json:"tag_id"`
}

// 1 row = new link, 0 = already linked (D-21). The cap trigger enforces the
// 10-tag limit; this statement never counts.
func (q *Queries) AttachTag(ctx context.Context, arg AttachTagParams) (int64, error) {
	result, err := q.db.Exec(ctx, attachTag, arg.ArtistID, arg.TagID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countCarriers = `-- name: CountCarriers :one
SELECT count(w.id)::bigint AS carrier_count
FROM artist_tags link
JOIN watchlist w ON w.artist_id = link.artist_id
WHERE link.tag_id = $1
`

// Watched carriers of one tag, for the merge target's post-merge count.
func (q *Queries) CountCarriers(ctx context.Context, tagID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countCarriers, tagID)
	var carrier_count int64
	err := row.Scan(&carrier_count)
	return carrier_count, err
}

const countCarriersForTags = `-- name: CountCarriersForTags :one
SELECT count(DISTINCT w.artist_id)::bigint AS carrier_count
FROM artist_tags link
JOIN watchlist w ON w.artist_id = link.artist_id
WHERE link.tag_id = ANY($1::bigint[])
`

// Watched carriers across the given tags, each artist counted once (D-19).
func (q *Queries) CountCarriersForTags(ctx context.Context, tagIds []int64) (int64, error) {
	row := q.db.QueryRow(ctx, countCarriersForTags, tagIds)
	var carrier_count int64
	err := row.Scan(&carrier_count)
	return carrier_count, err
}

const deleteDuplicateSourceLinks = `-- name: DeleteDuplicateSourceLinks :execrows
DELETE FROM artist_tags src
WHERE src.tag_id = $1
  AND EXISTS (
    SELECT 1 FROM artist_tags dup
    WHERE dup.artist_id = src.artist_id AND dup.tag_id = $2
  )
`

type DeleteDuplicateSourceLinksParams struct {
	SourceID int64 `json:"source_id"`
	TargetID int64 `json:"target_id"`
}

// Drops source links for artists already carrying the target, which would
// otherwise duplicate once RepointSourceLinks runs.
func (q *Queries) DeleteDuplicateSourceLinks(ctx context.Context, arg DeleteDuplicateSourceLinksParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDuplicateSourceLinks, arg.SourceID, arg.TargetID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTag = `-- name: DeleteTag :execrows
DELETE FROM tags WHERE id = $1
`

func (q *Queries) DeleteTag(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTag, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTagCountingCarriers = `-- name: DeleteTagCountingCarriers :one
WITH counted AS (
    SELECT count(w.id)::bigint AS carrier_count
    FROM artist_tags link
    JOIN watchlist w ON w.artist_id = link.artist_id
    WHERE link.tag_id = $1
), deleted AS (
    DELETE FROM tags WHERE id = $1 RETURNING id
)
SELECT deleted.id, counted.carrier_count FROM deleted, counted
`

type DeleteTagCountingCarriersRow struct {
	ID           int64 `json:"id"`
	CarrierCount int64 `json:"carrier_count"`
}

// Both CTEs share one snapshot, so counted never sees deleted's cascade and
// reports the carriers the delete removed (TAG-06). Zero rows = no such tag.
func (q *Queries) DeleteTagCountingCarriers(ctx context.Context, tagID int64) (DeleteTagCountingCarriersRow, error) {
	row := q.db.QueryRow(ctx, deleteTagCountingCarriers, tagID)
	var i DeleteTagCountingCarriersRow
	err := row.Scan(&i.ID, &i.CarrierCount)
	return i, err
}

const detachTag = `-- name: DetachTag :execrows
DELETE FROM artist_tags WHERE artist_id = $1 AND tag_id = $2
`

type DetachTagParams struct {
	ArtistID int64 `json:"artist_id"`
	TagID    int64 `json:"tag_id"`
}

// Any affected count is success; 0 rows means the link was already gone (D-21).
func (q *Queries) DetachTag(ctx context.Context, arg DetachTagParams) (int64, error) {
	result, err := q.db.Exec(ctx, detachTag, arg.ArtistID, arg.TagID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOrCreateTag = `-- name: GetOrCreateTag :one
INSERT INTO tags (name) VALUES ($1)
ON CONFLICT ((lower(name))) DO UPDATE SET name = tags.name
RETURNING id, name
`

type GetOrCreateTagRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

// No fallback SELECT (D-29): the no-op DO UPDATE makes RETURNING yield the
// existing row on a collision, keeping its first-entered casing.
func (q *Queries) GetOrCreateTag(ctx context.Context, name string) (GetOrCreateTagRow, error) {
	row := q.db.QueryRow(ctx, getOrCreateTag, name)
	var i GetOrCreateTagRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, name FROM tags WHERE lower(name) = lower($1)
`

type GetTagByNameRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

// Only after a tags_name_lower_idx violation, to identify the collider (D-22).
func (q *Queries) GetTagByName(ctx context.Context, lower string) (GetTagByNameRow, error) {
	row := q.db.QueryRow(ctx, getTagByName, lower)
	var i GetTagByNameRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getWatchlistArtistID = `-- name: GetWatchlistArtistID :one
SELECT artist_id FROM watchlist WHERE id = $1
`

// Resolves a watchlist entry's artist; artist_tags keys on artists.id (TAG-07).
func (q *Queries) GetWatchlistArtistID(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, getWatchlistArtistID, id)
	var artist_id int64
	err := row.Scan(&artist_id)
	return artist_id, err
}

const listTags = `-- name: ListTags :many
SELECT t.id, t.name, count(w.id)::bigint AS carrier_count
FROM tags t
LEFT JOIN artist_tags link ON link.tag_id = t.id
LEFT JOIN watchlist w ON w.artist_id = link.artist_id
GROUP BY t.id, t.name
ORDER BY lower(t.name), t.id
`

type ListTagsRow struct {
	ID           int64  `json:"id"`
	Name         string `json:"name"`
	CarrierCount int64  `json:"carrier_count"`
}

// count(w.id) counts only matched watchlist rows, so tags carried solely by
// removed artists, or by none, still list with 0 instead of being dropped by
// an inner join (D-11). lower(name) is unique, so the order is total.
func (q *Queries) ListTags(ctx context.Context) ([]ListTagsRow, error) {
	rows, err := q.db.Query(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagsRow
	for rows.Next() {
		var i ListTagsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.CarrierCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTagsForMerge = `-- name: LockTagsForMerge :many

SELECT id, name FROM tags WHERE id = ANY($1::bigint[]) ORDER BY id FOR UPDATE
`

type LockTagsForMergeRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

// Merge statement order and why it never inserts: ADR 0004.
// Locks both tags in id order so concurrent merges cannot deadlock; it also
// parks a concurrent attach/rename until commit.
func (q *Queries) LockTagsForMerge(ctx context.Context, ids []int64) ([]LockTagsForMergeRow, error) {
	rows, err := q.db.Query(ctx, lockTagsForMerge, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockTagsForMergeRow
	for rows.Next() {
		var i LockTagsForMergeRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameTag = `-- name: RenameTag :one
UPDATE tags SET name = $2 WHERE id = $1 RETURNING id, name
`

type RenameTagParams struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type RenameTagRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

// No collision pre-check: a tags_name_lower_idx unique violation is mapped
// to *CollisionError by Service.Rename (D-22).
func (q *Queries) RenameTag(ctx context.Context, arg RenameTagParams) (RenameTagRow, error) {
	row := q.db.QueryRow(ctx, renameTag, arg.ID, arg.Name)
	var i RenameTagRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const repointSourceLinks = `-- name: RepointSourceLinks :execrows
UPDATE artist_tags SET tag_id = $1 WHERE tag_id = $2
`

type RepointSourceLinksParams struct {
	TargetID int64 `json:"target_id"`
	SourceID int64 `json:"source_id"`
}

// Repoints the remaining links via UPDATE, never INSERT (ADR 0004).
func (q *Queries) RepointSourceLinks(ctx context.Context, arg RepointSourceLinksParams) (int64, error) {
	result, err := q.db.Exec(ctx, repointSourceLinks, arg.TargetID, arg.SourceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
