// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: watchlist.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWatchlistEntry = `-- name: CreateWatchlistEntry :one
INSERT INTO watchlist (artist_id, release_types, muted_event_types)
VALUES ($1, $2, $3)
RETURNING id, artist_id, release_types, muted_event_types, created_at, updated_at
`

type CreateWatchlistEntryParams struct {
	ArtistID        int64    `json:"artist_id"`
	ReleaseTypes    []string `json:"release_types"`
	MutedEventTypes []string `json:"muted_event_types"`
}

func (q *Queries) CreateWatchlistEntry(ctx context.Context, arg CreateWatchlistEntryParams) (Watchlist, error) {
	row := q.db.QueryRow(ctx, createWatchlistEntry, arg.ArtistID, arg.ReleaseTypes, arg.MutedEventTypes)
	var i Watchlist
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.ReleaseTypes,
		&i.MutedEventTypes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWatchlistEntry = `-- name: DeleteWatchlistEntry :execrows
DELETE FROM watchlist WHERE id = $1
`

// :execrows returns the affected row count in one round trip, which is what
// lets the service distinguish "deleted" from "there was nothing to delete"
// without a preceding existence SELECT. A check-then-delete pair would open
// a window where a concurrent delete lands between the two statements,
// turning what should be one 204 and one 404 into two 204s; Postgres's
// row-level lock on this single statement is what makes the split
// deterministic under concurrency (T-02-15).
func (q *Queries) DeleteWatchlistEntry(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWatchlistEntry, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listWatchlist = `-- name: ListWatchlist :many
SELECT w.id AS id, a.id AS artist_id, a.mbid, a.name, a.deezer_id,
       a.disambiguation, a.image_url,
       w.release_types, w.muted_event_types, w.created_at, w.updated_at
FROM watchlist w
JOIN artists a ON a.id = w.artist_id
ORDER BY a.name ASC, a.id ASC
`

type ListWatchlistRow struct {
	ID              int64              `json:"id"`
	ArtistID        int64              `json:"artist_id"`
	Mbid            string             `json:"mbid"`
	Name            string             `json:"name"`
	DeezerID        *string            `json:"deezer_id"`
	Disambiguation  *string            `json:"disambiguation"`
	ImageUrl        *string            `json:"image_url"`
	ReleaseTypes    []string           `json:"release_types"`
	MutedEventTypes []string           `json:"muted_event_types"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

// Both watchlist and artists have a column named id -- every selected
// column is explicitly aliased so sqlc emits a struct carrying both ID
// (the watchlist entry) and ArtistID (the master artist) rather than
// silently collapsing them (02-RESEARCH.md Pitfall 4). Name is not unique,
// so the artist id is a required, not cosmetic, ORDER BY tiebreak: without
// it, two equally-named artists would come back in whatever order the
// planner happens to choose, which is non-deterministic across runs.
func (q *Queries) ListWatchlist(ctx context.Context) ([]ListWatchlistRow, error) {
	rows, err := q.db.Query(ctx, listWatchlist)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWatchlistRow
	for rows.Next() {
		var i ListWatchlistRow
		if err := rows.Scan(
			&i.ID,
			&i.ArtistID,
			&i.Mbid,
			&i.Name,
			&i.DeezerID,
			&i.Disambiguation,
			&i.ImageUrl,
			&i.ReleaseTypes,
			&i.MutedEventTypes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWatchlistPreferences = `-- name: UpdateWatchlistPreferences :one
WITH updated AS (
    UPDATE watchlist
    SET release_types = CASE
            WHEN $1::boolean THEN $2::text[]
            ELSE watchlist.release_types
        END,
        muted_event_types = CASE
            WHEN $3::boolean THEN $4::text[]
            ELSE watchlist.muted_event_types
        END,
        updated_at = now()
    WHERE watchlist.id = $5
    RETURNING watchlist.id, watchlist.artist_id, watchlist.release_types, watchlist.muted_event_types, watchlist.created_at, watchlist.updated_at
)
SELECT u.id AS id, a.id AS artist_id, a.mbid, a.name, a.deezer_id,
       a.disambiguation, a.image_url,
       u.release_types, u.muted_event_types, u.created_at, u.updated_at
FROM updated u
JOIN artists a ON a.id = u.artist_id
`

type UpdateWatchlistPreferencesParams struct {
	SetReleaseTypes    bool     `json:"set_release_types"`
	ReleaseTypes       []string `json:"release_types"`
	SetMutedEventTypes bool     `json:"set_muted_event_types"`
	MutedEventTypes    []string `json:"muted_event_types"`
	ID                 int64    `json:"id"`
}

type UpdateWatchlistPreferencesRow struct {
	ID              int64              `json:"id"`
	ArtistID        int64              `json:"artist_id"`
	Mbid            string             `json:"mbid"`
	Name            string             `json:"name"`
	DeezerID        *string            `json:"deezer_id"`
	Disambiguation  *string            `json:"disambiguation"`
	ImageUrl        *string            `json:"image_url"`
	ReleaseTypes    []string           `json:"release_types"`
	MutedEventTypes []string           `json:"muted_event_types"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

// The partial-update merge happens inside this statement, not in Go: each
// axis is resolved by a CASE whose ELSE names the column itself, so the
// value carried forward for an untouched axis is read from the row version
// this UPDATE itself locked. Under READ COMMITTED a writer blocked behind
// another writer's uncommitted change re-evaluates its WHERE clause and SET
// expressions against the newly committed row once it unblocks -- so the
// second writer physically cannot persist a value it observed before the
// first writer committed (G-02-2b, T-02-19). The zero-row case (no matching
// id, including one deleted concurrently) surfaces as pgx.ErrNoRows, which
// Service.UpdatePreferences translates to ErrNotFound in one round trip
// (T-02-20) -- there is no separate unlocked read whose result can go stale.
//
// Each axis's "am I being set" signal is carried by its own explicit boolean
// parameter rather than multiplexed onto the array parameter's nullability:
// an empty array and an absent key are two different client intents (D-11),
// and a NULL-means-untouched COALESCE would collapse that distinction.
func (q *Queries) UpdateWatchlistPreferences(ctx context.Context, arg UpdateWatchlistPreferencesParams) (UpdateWatchlistPreferencesRow, error) {
	row := q.db.QueryRow(ctx, updateWatchlistPreferences,
		arg.SetReleaseTypes,
		arg.ReleaseTypes,
		arg.SetMutedEventTypes,
		arg.MutedEventTypes,
		arg.ID,
	)
	var i UpdateWatchlistPreferencesRow
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.Mbid,
		&i.Name,
		&i.DeezerID,
		&i.Disambiguation,
		&i.ImageUrl,
		&i.ReleaseTypes,
		&i.MutedEventTypes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
