// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: watchlist.sql

package sqlc

import (
	"context"
)

const createWatchlistEntry = `-- name: CreateWatchlistEntry :one
INSERT INTO watchlist (artist_id, release_types, muted_event_types)
VALUES ($1, $2, $3)
RETURNING id, artist_id, release_types, muted_event_types, created_at, updated_at
`

type CreateWatchlistEntryParams struct {
	ArtistID        int64    `json:"artist_id"`
	ReleaseTypes    []string `json:"release_types"`
	MutedEventTypes []string `json:"muted_event_types"`
}

func (q *Queries) CreateWatchlistEntry(ctx context.Context, arg CreateWatchlistEntryParams) (Watchlist, error) {
	row := q.db.QueryRow(ctx, createWatchlistEntry, arg.ArtistID, arg.ReleaseTypes, arg.MutedEventTypes)
	var i Watchlist
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.ReleaseTypes,
		&i.MutedEventTypes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
